### ISSUE TITLE
AppWiki

### ISSUE THREAD

**Issue by fschott25** [mobileappdevhm19/ILA-Flutter#68]
**For who?**
For everyone to read the instructions for the app

**Describe the feature**
A page where you can find all the informations to work with the app 

**Acceptance criteria**
Everything has to be discribed clearly 

the wiki contains the following pages:
- [x] Login
- [x] Registration 
- [x] Home 
- [x] Course
- [x] News
- [x] Lecture
- [x] Settings

**Comment by KirschbaumP** [comment]
Could you defie a list with all pages you want to create?
like:
- [ ] Login
- [ ] Registration
- [ ] ...
